### ISSUE TITLE
Permissions changes

### ISSUE THREAD

**Issue by CBenghi** [xBimTeam/XbimGltf#1]
Hi @andyward,

after your comment on the xplorer plugins compatibility issue I've been going through the various repositories to update the binaries and I seem to have lost access to this one, as I have an updated that I need to push.

I wonder if you know of any permission changes that might have affected this. 

I've noticed that I'm not listed as a maintainer on the xbimteam, while Steve, Martin and you are.
Might that be the reason?

Thanks,
Claudio

**Comment by martin1cerny** [comment]
Hi Claudio, Steve made some changes to the structure of the GitHub team. I checked and the problem was that after these changes there was actually no team assigned to XbimGltf project. You should be able all you need with it now. As a member of the Core team you are admin of the repository.

**Comment by CBenghi** [comment]
thanks @martin1cerny,
it worked.
Speak to you soon.
