### ISSUE TITLE
BuildingModelExtractors.cs may have IFC2X3 in line 48 by mistake

### ISSUE THREAD

**Issue by TomConstru** [xBimTeam/XbimGltf#12]
This might be a bug, at the end of the line, shouldn't it be Xbim.Properties.Version.IFC4 ?
`
case "ifc4":
propertyDefinitions = new Definitions<PropertySetDef>(Xbim.Properties.Version.IFC2x3);
`
in this [line](https://github.com/xBimTeam/XbimGltf/blob/41fecca9fc275c3e124bbda12e71c3979e91e98f/Xbim.GLTF.IO/SemanticExport/BuildingModelExtractor.cs#L48)

**Comment by CBenghi** [comment]
Thanks, @TomConstru.
Well spotted.
