### ISSUE TITLE
BuildingModelExtractor.cs line 207 & 212 throws exception when NominalValue is null

### ISSUE THREAD

**Issue by TomConstru** [xBimTeam/XbimGltf#13]
In this place https://github.com/xBimTeam/XbimGltf/blob/27cced4eee35a11ab7fbe59fd6dae70d9fb5701a/Xbim.GLTF.IO/SemanticExport/BuildingModelExtractor.cs#L207

I suggest to change in both line 207 and 212 the if statement to:
`if (found != null && found.NominalValue != null)`

In my case I had IfcFireRating($,$,$) and IfcDescription($,$,$) in my IFC file that threw exceptions in the semantic export. This change to the if statement solved it.

**Comment by CBenghi** [comment]
It makes perfect sense. Thanks @TomConstru 
Fixed.
