### ISSUE TITLE
Reduce GLTF generation time to 40%

### ISSUE THREAD

**Issue by tmarti** [xBimTeam/XbimGltf#2]
Following pieces of code...

https://github.com/xBimTeam/XbimGltf/blob/ce86371c5ca3e416023f785b772960661f50f90a/Xbim.GLTF.IO/Builder.cs#L519

https://github.com/xBimTeam/XbimGltf/blob/ce86371c5ca3e416023f785b772960661f50f90a/Xbim.GLTF.IO/XbimMesher.cs#L107-L109

... are setting the `Capacity` property of some `List` objects by hand.

As stated on https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.capacity?view=netframework-4.8:

> When the value of Capacity is set explicitly, the internal array is also reallocated to accommodate the specified capacity, and all the elements are copied. 

This means that setting the list `Capacity` by hand implies a memory reallocation+copy.

If, instead the referenced lines are simply removed, the `List` automatically increases its capacity (as more space for items is needed) in a much more efficient way (maybe doubling its `Capacity` whenever it needs more space (which would save many calls to increase it by hand), but not sure).

The result is that removing previous lines of code reduces the execution time for the `GLTF` generation part of the export process to 40% of the original time, in case of a relatively small `xBIM`file (18MB) file (from 9.7s to 3.8s on a quick test scenario) 😃

**Comment by CBenghi** [comment]
You're very right, will do soon.
