### ISSUE TITLE
Work with command line

### ISSUE THREAD

**Issue by vladimir-iukhimenko** [xBimTeam/XbimGltf#20]
Hello,

Could you please explain how to work with Xbim Xplorer in cmd? I want to convert ifc to gltf via Gltf Explorer, can I make convertion without using UI, only with commands in terminal?

Thanks in advance.

**Comment by gcoulby** [comment]
Hi @vladimir-iukhimenko.  Most of the open source Xbim tools are available from the Commandline.  

While the Gltf package does provide a plugin support through Xbim Xplorer, the core functionality of the code is available through CLI.

First, install the library as a NuGet package using the command from the documentation.

`Install-Package Xbim.Gltf.IO -Version 4.0.1-V0007 -Source https://www.myget.org/F/xbim-develop/api/v3/index.json`

Most (if not all) Xbim libraries provide comprehensive UnitTests of the functionality. If you read the following source code (https://github.com/xBimTeam/XbimGltf/blob/develop/MainTests/ConversionTests.cs) you will see that what you are asking is available: 

Here is the test abstracted into a console application (just change the ifc variable to point to your file): 

```c#
using System.IO;
using Xbim.Common.Geometry;
using Xbim.GLTF;
using Xbim.Ifc;
using Xbim.ModelGeometry.Scene;

namespace xbim.gltf
{
    class Program
    {
        static void Main(string[] args)
        {
            var ifc = new FileInfo("OneWallTwoWindows.ifc");
            var xbim = CreateGeometry(ifc, true, false);

            using (var s = IfcStore.Open(xbim.FullName))
            {
                var savename = Path.ChangeExtension(s.FileName, ".gltf");
                var bldr = new Builder();
                var ret = bldr.BuildInstancedScene(s, XbimMatrix3D.Identity);
                glTFLoader.Interface.SaveModel(ret, savename);


                FileInfo f = new FileInfo(s.FileName);

                // write json
                //
                var jsonFileName = Path.ChangeExtension(s.FileName, "json");
                var bme = new Xbim.GLTF.SemanticExport.BuildingModelExtractor();
                var rep = bme.GetModel(s);
                rep.Export(jsonFileName);
            }
        }

        private static FileInfo CreateGeometry(FileInfo f, bool mode, bool useAlternativeExtruder)
        {
            using (var m = IfcStore.Open(f.FullName))
            {
                var c = new Xbim3DModelContext(m);
                c.CreateContext(null, mode);
                var newName = Path.ChangeExtension(f.FullName, mode + ".xbim");
                m.SaveAs(newName);
                return new FileInfo(newName);
            }
        }
    }
}
```

**Comment by vladimir-iukhimenko** [comment]
Hello @gcoulby, thank you for your fast reply. 
I've tried your code, but got:
`Unhandled exception. System.NotImplementedException: MemoryModelProvider is a transient store and does not support persistance
   at Xbim.IO.Memory.MemoryModelProvider.Persist(IModel model, String fileName, ReportProgressDelegate progDelegate)
   at Xbim.Ifc.IfcStore.SaveAs(String actualFileName, StorageType actualFormat, ReportProgressDelegate progDelegate)
   at Xbim.Ifc.IfcStore.SaveAs(String fileName, Nullable`1 format, ReportProgressDelegate progDelegate)`

I see in IfcStore class the following comment:

> To guarantee the correct provider regardless, configure <see cref="IfcStore.ModelProviderFactory"/> with the 
>     /// following code in your application initialisation:
>     /// <code>
>     /// IfcStore.ModelProviderFactory.UseHeuristicModelProvider();
>     /// </code>

but this method is not available. How this problem can be solved?

**Comment by gcoulby** [comment]
That's strange, I ran the code without any issues and converted to a GLTF successfully. The line of code you are referring to is referenced in the UnitTest, but I did not include it as my test worked. This line of code requires you to use the development packages for Geometry and also install the Xbim.IO.Esent develop package

to use 
`IfcStore.ModelProviderFactory.UseHeuristicModelProvider();`

match your NuGet packages to the UnitTest:
```
Xbim.Geometry v5.1.403 (develop)
Xbim.IO.Esent v5.1.323 (develop)
```

However, **Please note** it is not recommended to work off the development packages in production as they frequently change and likely wont provide deprecation notices etc.

**Comment by vladimir-iukhimenko** [comment]
Finally I ran the code and it generated GLTF, thank you for your help! Is there any restrictions for input IFC file? (file size, etc.)

**Comment by gcoulby** [comment]
That I don't know the answer to, this is the first time I have looked at the GLTF package. However, Xbim can work with very large IFCs

**Comment by CBenghi** [comment]
For large files I'd suggests to break down the export in several gltf files
that you can then load as you wish.

In principle there is no limitation.


Il Mer 7 Apr 2021, 20:20 GrahamCoulby ***@***.***> ha scritto:
