### ISSUE TITLE
NuGet Feed Not Updated

### ISSUE THREAD

**Issue by rade-tomovic** [xBimTeam/XbimGltf#22]
It seems that the latest version for Xbim.Gltf.IO is V0008, but NuGet feed is still stuck at V0007 (based on command below from official documentation):
`Install-Package Xbim.Gltf.IO -Version 4.0.1-V0007 -Source https://www.myget.org/F/xbim-develop/api/v3/index.json`

Can you please check for the latest version since we need the latest updated which resolves null handling in certain scenarios?

Thanks

**Comment by CBenghi** [comment]
Yes.
Later tonight I'll do that

Il Dom 25 Apr 2021, 12:03 Rade Tomovic ***@***.***> ha
scritto:

**Comment by CBenghi** [comment]
Hi,
I've updated the packages and later noticed that you are using quite an old version.
Version 4.x are outdated.

The versions are 5.x.

Is there a problem for you updating?

**Comment by rade-tomovic** [comment]
It's not, but what is the latest version I should reference? Readme file still points out to v4.0.1-V0007 (under Usage header there is an explanation referencing that the best way to use library is through NuGet with specified source). It's not a problem using it by referencing this as a submodule, but if there is a way to use it as NuGet, I'd rather go that way.

**Comment by CBenghi** [comment]
I've updated the readme on master branch.
That uses a completely new version of the entire stack.
Have a look, let me know if this works for you.

**Comment by rade-tomovic** [comment]
It's working now, thank you for your help :)
