### ISSUE TITLE
3dTiles files

### ISSUE THREAD

**Issue by luyongqiang** [xBimTeam/XbimGltf#3]
Can you generate 3dtiles files? Thank you

**Comment by alex4wtr** [comment]
just some thoughts: 

- https://github.com/sellingsolutions/ifc2b3dm/tree/master/GLTFs2B3DM
- https://github.com/bertt/b3dm-tile-cs

**Comment by luyongqiang** [comment]
Thanks @alex4wtr

**Comment by luyongqiang** [comment]
Thanks @alex4wtr
