### ISSUE TITLE
Clarification of "what is this number" comment

### ISSUE THREAD

**Issue by tmarti** [xBimTeam/XbimGltf#4]
In the following piece of code:

https://github.com/xBimTeam/XbimGltf/blob/0df1f82e8c8ac845c4c5ae1c6f269574ea6ff09b/Xbim.GLTF.IO/Builder.cs#L63

There is the following comment:

> // todo: what is this number?

The stride (https://en.wikipedia.org/wiki/Stride_of_an_array), is the distance in bytes from one element to the next in a in-memory buffer.

Each coordinate is a float32 (4 bytes), and each position has 3 coordinates (X, Y, Z).

So the distance in bytes in `glTFLoader.Schema.BufferView` between each consecutive position:
> (4 bytes / coordinate) * (3 coordinates / position) = 12 bytes / position = stride

Just a silly issue to be created, I know, but hopefully can get rid of that _todo: what is this number_ comment 🙃

**Comment by CBenghi** [comment]
Lol, 
thanks @tmarti, addressed in 80cac965bfb355e7cffec1cac76e7b99a1206c5f.
;-)

**Comment by tmarti** [comment]
Oh! People have now replaced the question "what is this comment?" with "who is @tmarti?"

https://github.com/xBimTeam/XbimGltf/blob/80cac965bfb355e7cffec1cac76e7b99a1206c5f/Xbim.GLTF.IO/Builder.cs#L63

😆

**Comment by CBenghi** [comment]
It will need a wikipedia page!
