### ISSUE TITLE
normal error 

### ISSUE THREAD

**Issue by veyvin** [xBimTeam/XbimGltf#5]
the ifc
[abc.zip](https://github.com/xBimTeam/XbimGltf/files/4004821/abc.zip)

and the gltf

[abcgltf.zip](https://github.com/xBimTeam/XbimGltf/files/4004823/abcgltf.zip)

![image](https://user-images.githubusercontent.com/6776758/71510498-248dd080-28ca-11ea-87fb-5339e397dc08.png)
![image](https://user-images.githubusercontent.com/6776758/71510564-49824380-28ca-11ea-9b07-041b17e7d3eb.png)

**Comment by CBenghi** [comment]
Hello,
it's not clear to me what the problem is.
Your arrows are pointing at different parts on the model.
Can you clarify?
Thanks

**Comment by veyvin** [comment]
it's a plane ,have 4 vertices 2 triangle.   In xbim xplorer call  表面598663 #78024
![image](https://user-images.githubusercontent.com/6776758/71556488-488d1580-2a74-11ea-944d-a0c80cb27f68.png)

its back face  is visual， the front is  Transparent

**Comment by veyvin** [comment]
@CBenghi  set  m.DoubleSided = true;  in Builder.cs ,it's correct

![image](https://user-images.githubusercontent.com/6776758/71565030-fe904800-2ae4-11ea-965b-ba5bcaa97083.png)

**another ifc model**
[IfcOpenHouseGeoRef.zip](https://github.com/xBimTeam/XbimGltf/files/4008786/IfcOpenHouseGeoRef.zip)

DoubleSided = true;
![image](https://user-images.githubusercontent.com/6776758/71565037-1667cc00-2ae5-11ea-89fe-bab65842b490.png)

DoubleSided = false;
![image](https://user-images.githubusercontent.com/6776758/71565047-3e572f80-2ae5-11ea-9090-f65a681597eb.png)

**Comment by veyvin** [comment]
@CBenghi  maybe use opencascade get vertex ,the indices error

this maybe helpful
```cpp
Standard_Integer v1, v2, v3;
				for (unsigned int j = 1; j <= noOfTriangles; j++)
				{
					**if (face.Orientation() == TopAbs_REVERSED)**
					{
						triangles(j).Get(v1, v3, v2);
						
					}
					else
					{
						triangles(j).Get(v1, v2, v3);
					}

......
```

**Comment by veyvin** [comment]
maybe the indices is error

**Comment by CBenghi** [comment]
Hello @veyvin,
I've posted an update that should fix your problem without setting every material to double sided.
Hope it helps, sorry for the delay, this was a bit of a corner case.
Best,
Claudio
