### ISSUE TITLE
Material

### ISSUE THREAD

**Issue by SaHajizadeh** [xBimTeam/XbimGltf#9]
Hi,

As you know, an element in Revit can have multiple material. for example, a wall can have two different materials on the Exterior sides. but when i convert the IFC file to GLTF format, an element(Mesh) only have a primitive. I would be thankful if you help me how to fix this. 
IFC file save the materials of an element in IFCMaterialLayerSet though.

Bellow figure shows an example of a mesh in GLTF file with three different materials.

![Mesh](https://user-images.githubusercontent.com/58989847/88259614-e9c10f00-ccd7-11ea-921f-40862d6ad1ae.PNG)

thank you.

**Comment by martin1cerny** [comment]
IFC takes slightly different view on this. Materials and appearance are more separate in IFC. Element has a material as one of its semantic attributes. Also element has a geometry representation which consists of a group of shapes in certain geometric context. Shapes can have a style. Also, single material might have a style but most of the elements consist of multiple materials (either as layers, or other compound). The key entity is [IfcStyledItem](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcstyleditem.htm). So, you will want to have a look at these styles and how much Revit exports from its internal structures.

**Comment by SaHajizadeh** [comment]
> IFC takes slightly different view on this. Materials and appearance are more separate in IFC. Element has a material as one of its semantic attributes. Also element has a geometry representation which consists of a group of shapes in certain geometric context. Shapes can have a style. Also, single material might have a style but most of the elements consist of multiple materials (either as layers, or other compound). The key entity is [IfcStyledItem](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcstyleditem.htm). So, you will want to have a look at these styles and how much Revit exports from its internal structures.


Unfortunately, I did not understand what you meant. I read about IfcStyleItem which you mentioned, but i couldn't fix my problem.

**Comment by martin1cerny** [comment]
What I wanted to say is, that there is a mismatch between how material and representation is modelled in IFC and in Revit. So, you will need to make sure that the right information is actually exported from Revit to IFC. Once you are sure the information is available in IFC, you can have a look at how to extract it from IFCto glTF using xbim. Xbim implements 100% of the schema, so if the data is in IFC, you will have access to it.

**Comment by martin1cerny** [comment]
I just realised there is another corner to your question. Walls are usually exported as a single element from Revit to IFC and they have single colour regardless of the material on either side. This is different with some configurations of IFC4 export where colours are stored against faces instead of shapes.

**Comment by SaHajizadeh** [comment]
> I just realised there is another corner to your question. Walls are usually exported as a single element from Revit to IFC and they have single colour regardless of the material on either side. This is different with some configurations of IFC4 export where colours are stored against faces instead of shapes.


Thanks for your consideration,
So, is there any way to assign different color or material on either side?

**Comment by martin1cerny** [comment]
If the wall is modelled as an extruded area solid, then you could go to material layer set, get materials on both sides and try to get the style for these materials (see the diagram bellow). If it is modelled as `IfcClosedShell`, then every face can potentially have different style.
![IfcStyledItem](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/figures/ifcstyleditem_fig-1.png)

**Comment by SaHajizadeh** [comment]
> If the wall is modelled as an extruded area solid, then you could go to material layer set, get materials on both sides and try to get the style for these materials (see the diagram bellow). If it is modelled as `IfcClosedShell`, then every face can potentially have different style.
> ![IfcStyledItem](https://camo.githubusercontent.com/9d0c09d0ef9351615e716b2a849831ea1eb4d0ee/68747470733a2f2f7374616e64617264732e6275696c64696e67736d6172742e6f72672f4946432f52454c454153452f494643342f414444325f5443312f48544d4c2f666967757265732f6966637374796c65646974656d5f6669672d312e706e67)

thank you, 
I checked it but it didn't work.
i think you did not consider it in your codes for some reason, 
maybe it can not be done with ifc to gltf converter.
Is it possible to be kind and share this with your team if it is possible or not?

thanks for your help

**Comment by martin1cerny** [comment]
Yes, this is not considered in our code. I was describing how you could improve it yourself. We don't plan to support multiple styles for a single shape at the moment. But this is all open source, so you are welcome to contribute to give back to the community.

**Comment by SaHajizadeh** [comment]
thanks again for your help.
